/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VuePnl;

import Metier.ClsDetailPaiement;
import Metier.ClsPaiement;
import Vue.FrmPrincipal;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author gloire
 */
public class PnlPaiement extends javax.swing.JPanel {

    /**
     * Creates new form PnlInscription
     */
    int txtId;
    public PnlPaiement() throws ClassNotFoundException, SQLException {
        initComponents();
        txtiddetpaie.setText("DP00"+Dao.CllsUpdateAll.Incrementation("detailpaiement "));
        txtid.setText("Pa00"+Dao.CllsUpdateAll.Incrementation("paiement "));
        Dao.CllsUpdateAll.ChargerText(txtId, "SELECT montant FROM provisionfrais");
        String so = String.valueOf(txtId);
//        txttotalpaie.setText(so);
        Dao.CllsUpdateAll.ChargerTablePaiement( jTable1);
        txtidinscrit.setVisible(false);
        txtid.setVisible(false);
        txtiddet.setVisible(false);
        jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbtype = new javax.swing.JComboBox();
        txtiddetpaie = new javax.swing.JTextField();
        txtmontant = new javax.swing.JTextField();
        txtidinscrit = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtidel1 = new javax.swing.JTextField();
        txtiddet = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtidel2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        classe = new javax.swing.JTextField();

        setBackground(new java.awt.Color(26, 145, 202));
        setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel30.setForeground(java.awt.Color.white);
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("INFORMATION SUR LE PAIEMENT");

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jTable1.setForeground(null);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cbtype.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        cbtype.setForeground(null);
        cbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Premier trimestre", "Deuxieme trimestre", "Troisieme trimestre", "Autres frais" }));

        txtiddetpaie.setBackground(new java.awt.Color(67, 156, 230));
        txtiddetpaie.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtiddetpaie.setForeground(null);
        txtiddetpaie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtmontant.setBackground(new java.awt.Color(67, 156, 230));
        txtmontant.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtmontant.setForeground(null);
        txtmontant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmontant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontantKeyTyped(evt);
            }
        });

        txtidinscrit.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtidinscrit.setForeground(null);

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Montant");

        txtid.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtid.setForeground(null);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("EFFECTUER PAIEMENT");

        jButton3.setBackground(java.awt.Color.gray);
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("MODIFIER");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.gray);
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("ENREGISTRER");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel28.setForeground(java.awt.Color.white);
        jLabel28.setText("Type paiement");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Entrez l'id de l'eleve");

        txtidel1.setBackground(new java.awt.Color(67, 156, 230));
        txtidel1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtidel1.setForeground(null);
        txtidel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtidel1MouseExited(evt);
            }
        });
        txtidel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidel1KeyTyped(evt);
            }
        });

        txtiddet.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtiddet.setForeground(null);

        jButton2.setBackground(java.awt.Color.gray);
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PrinterNetwork_32x32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Noms");

        txtidel2.setBackground(new java.awt.Color(67, 156, 230));
        txtidel2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtidel2.setForeground(null);
        txtidel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtidel2MouseExited(evt);
            }
        });
        txtidel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidel2KeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel29.setForeground(java.awt.Color.white);
        jLabel29.setText("Classe");

        classe.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        classe.setForeground(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtidinscrit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(txtiddetpaie, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txtidel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(txtiddet, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(105, 105, 105)
                                .addComponent(classe, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(47, 47, 47)
                                .addComponent(cbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtiddetpaie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidinscrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtiddet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtidel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel24))
                        .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel28))
                            .addComponent(cbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel30)
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            ClsPaiement  p = new ClsPaiement();
            ClsDetailPaiement dp = new ClsDetailPaiement();
            
            p.setIdpaie(txtid.getText());
            
            dp.setIddetail(txtiddetpaie.getText());
            dp.setMontant(Integer.parseInt(txtmontant.getText()));
            dp.setDatepaie(FrmPrincipal.viewdate.getText());
            dp.setTypepaie((String) cbtype.getSelectedItem());
            dp.setPaiement(txtid.getText());

            if (p.Modifier() && dp.Modifier())
            {
                JOptionPane.showMessageDialog(null, "Modification reussi", "Reussi", JOptionPane.INFORMATION_MESSAGE);
                Dao.CllsUpdateAll.ChargerTablePaiement(jTable1);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur dans la odification", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            ClsPaiement  p = new ClsPaiement();
            ClsDetailPaiement dp = new ClsDetailPaiement();
            
            p.setIdpaie(txtid.getText());
            p.setDetail(txtiddet.getText());
            
            dp.setIddetail(txtiddetpaie.getText());
            dp.setMontant(Integer.parseInt(txtmontant.getText()));
            dp.setDatepaie(FrmPrincipal.viewdate.getText());
            dp.setTypepaie((String) cbtype.getSelectedItem());
            dp.setPaiement(txtid.getText());
           

            if (p.Enregistrer()&& dp.Enregistrer())
            {
                JOptionPane.showMessageDialog(null, "Enregistrement reussi", "Reussi", JOptionPane.INFORMATION_MESSAGE);
                Dao.CllsUpdateAll.ChargerTablePaiement(jTable1);     
            }
            else
               JOptionPane.showMessageDialog(null, "Erreur d'enregistrement", "Erreur", JOptionPane.ERROR_MESSAGE); 
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Eleve '"+txtidel1.getText()+"' n'existe pas!", "Erreur dans l'insertion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtidel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidel1KeyTyped
        
//        try {
//            Dao.CllsUpdateAll.ChargerTextField(txtid, "SELECT idinsc FROM inscrire  WHERE eleve = '"+ txtidel1.getText() +"'");
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(PnlPaiement.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(PnlPaiement.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        System.out.println(txtIdInscrire);
    }//GEN-LAST:event_txtidel1KeyTyped

    private void txtidel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidel1MouseExited
        try {
            Dao.CllsUpdateAll.ChargerTextField(txtidinscrit, "SELECT idinsc FROM inscrire  WHERE eleve = '"+ txtidel1.getText() +"'"); 
             Dao.CllsUpdateAll.ChargerTextField(txtiddet, "SELECT iddet FROM detail  WHERE inscrit = '"+ txtidinscrit.getText() +"'"); 
             Dao.CllsUpdateAll.ChargerNoms(txtidel2, "SELECT CONCAT(nomel, ' ', postnomel, ' ', prenomel) "
                     + "FROM eleve WHERE idel = '"+txtidel1.getText()+"'");
             Dao.CllsUpdateAll.ChargerNoms
                        (classe, "SELECT cl.classe FROM eleve e INNER JOIN inscrire i ON i.eleve = e.idel INNER JOIN detail d "
                                + "ON d.inscrit = i.idinsc INNER JOIN categorie c ON c.idcat = d.categorie INNER JOIN classe cl ON cl.idclass = c.classe "
                                + "WHERE idel ='"+txtidel1.getText()+"'");
//        Dao.CllsUpdateAll.calculerFrais(txttotalpaie);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PnlPaiement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtidel1MouseExited

    private void txtmontantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontantKeyTyped
         try {
            Dao.CllsUpdateAll.ChargerTextField(txtidinscrit, "SELECT idinsc FROM inscrire  WHERE eleve = '"+ txtidel1.getText() +"'"); 
             Dao.CllsUpdateAll.ChargerTextField(txtiddet, "SELECT iddet FROM detail  WHERE inscrit = '"+ txtidinscrit.getText() +"'"); 
             Dao.CllsUpdateAll.ChargerNoms(txtidel2, "SELECT CONCAT(nomel, ' ', postnomel, ' ', prenomel) "
                     + "FROM eleve WHERE idel = '"+txtidel1.getText()+"'");
             Dao.CllsUpdateAll.ChargerNoms
                        (classe, "SELECT cl.classe FROM eleve e INNER JOIN inscrire i ON i.eleve = e.idel INNER JOIN detail d "
                                + "ON d.inscrit = i.idinsc INNER JOIN categorie c ON c.idcat = d.categorie INNER JOIN classe cl ON cl.idclass = c.classe "
                                + "WHERE idel ='"+txtidel1.getText()+"'");
//        Dao.CllsUpdateAll.calculerFrais(txttotalpaie);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PnlPaiement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtmontantKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        try {
//            boolean complet = txtiddetpaie.print() && txtidel1.print() && txtidel2.print() && classe.print() && txtmontant.print();
////            boolean id1 = ;
//            if (complet)
//                JOptionPane.showMessageDialog(null, "En cours d'impression", "Impression", JOptionPane.INFORMATION_MESSAGE);
//            else
//                JOptionPane.showMessageDialog(null, "Erreur survenu lors de l'impression", "Erreur", JOptionPane.ERROR_MESSAGE);
//        } catch (PrinterException ex) {
//            Logger.getLogger(PnlPaiement.class.getName()).log(Level.SEVERE, null, ex);
//        }
        JLabel lb = new JLabel();
                String req = "SELECT e.idel, e.nomel, e.postnomel, e.prenomel, cl.classe, \n" +
"dp.montant, dp.datepaie, dp.typepaie, dp.iddetail FROM  eleve e INNER JOIN inscrire i ON e.idel = i.eleve INNER JOIN detail d \n" +
"ON i.idinsc = d.inscrit INNER JOIN categorie c ON d.categorie = c.idcat INNER JOIN classe cl ON cl.idclass = c.classe \n" +
"INNER JOIN paiement p ON d.iddet = p.detail INNER JOIN detailpaiement dp ON p.idpaie = dp.paiement \n" +
"WHERE iddetail = '"+txtiddetpaie.getText()+"'";
        lb.setText("src//Rapport//Recu.jrxml");
        try {       
            Dao.CllsUpdateAll.print(lb, req);
        } catch (ClassNotFoundException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Une erreur est survenu lors de l'impression !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtidel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidel2MouseExited

    private void txtidel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidel2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidel2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbtype;
    private javax.swing.JTextField classe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtiddet;
    private javax.swing.JTextField txtiddetpaie;
    private javax.swing.JTextField txtidel1;
    private javax.swing.JTextField txtidel2;
    private javax.swing.JTextField txtidinscrit;
    private javax.swing.JTextField txtmontant;
    // End of variables declaration//GEN-END:variables
}
